# Generated by Django 2.2.6 on 2019-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_painting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='artist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
