# Generated by Django 2.2.6 on 2019-10-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20191020_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='painter',
            field=models.ImageField(blank=True, upload_to='assets/img'),
        ),
    ]
