# Generated by Django 2.2.6 on 2019-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20191021_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='pic',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
